name: test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 9 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@86823142467dd2afcd1bbac57d3a664cf468eb3b  # v2.1.0
    with:
      envs: |
        - linux: check-style
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@86823142467dd2afcd1bbac57d3a664cf468eb3b  # v2.1.0
    with:
      envs: |
        - linux: py311-oldestdeps
        - linux: py311
        - linux: py312
        # `tox` does not currently respect `requires-python` versions when creating testing environments;
        # if this breaks, add an upper pin to `requires-python` and revert this py3 to the latest working version
        - linux: py3-cov
          coverage: codecov
          pytest-results-summary: true
        - macos: py3
          pytest-results-summary: true
        - linux: py3-dev
